openapi: 3.0.1
info:
  title: Cargo Vehicle Ownership API
  version: 2.0.0
  description: 사업장 내 화물자동차 보유 현황

paths:
  /api/site-status/{siteId}/cargo-vehicles:
    get:
      summary: 화물자동차 목록 조회
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CargoVehicle'

    post:
      summary: 화물자동차 목록 일괄 등록 또는 수정
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CargoVehicle'
      responses:
        '200':
          description: 저장/수정 성공

    delete:
      summary: 화물자동차 전체 삭제
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 전체 삭제 성공

components:
  schemas:
    CargoVehicle:
      type: object
      properties:
        plateNumber:
          type: string
          example: "12나1111"
        model:
          type: string
          example: "포터"
        maxLoad:
          type: string
          example: "1톤"
        vehicleType:
          type: string
          example: "화물"
      required:
        - plateNumber
        - model
        - maxLoad
        - vehicleType