openapi: 3.0.1
info:
  title: Site Summary API
  version: 1.0.0
  description: 사업장 개요 - 전반적인 안전/물류/조직/사고/위험 설비 보유 상태 종합 관리

paths:
  /api/site-status/{siteId}/summary:
    get:
      summary: 사업장 개요 정보 조회
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteSummary'

    post:
      summary: 사업장 개요 정보 등록
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SiteSummary'
      responses:
        '200':
          description: 등록 성공

    put:
      summary: 사업장 개요 정보 수정
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SiteSummary'
      responses:
        '200':
          description: 수정 성공

    delete:
      summary: 사업장 개요 정보 삭제
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 삭제 성공

components:
  schemas:
    SiteSummary:
      type: object
      properties:
        siteStatus:
          type: string
          description: 사업장 상태 요약 ( 정상 운영, 일부 공정 중단 등)
          example: "정상 운영 중"
        accidentHistory:
          type: string
          description: 최근 산업재해 발생 여부 및 요약
          example: "2024년 2월 손가락 끼임 사고 1건 발생"
        safetyEquipmentOwned:
          type: string
          description: 보유한 안전장치 요약
          example: "감지기, 방호덮개, 정지버튼 보유"
        hazardousEquipmentOwned:
          type: string
          description: 유해/위험 설비 보유 여부 및 종류
          example: "프레스, 절단기"
        cargoVehicleOwned:
          type: boolean
          description: 화물자동차 보유 여부
          example: true
        safetyOrganizationAssigned:
          type: string
          description: 안전보건 조직 구성 여부
          example: "안전관리자, 보건관리자 배치 완료"
      required:
        - siteStatus
        - accidentHistory
        - safetyEquipmentOwned
        - hazardousEquipmentOwned
        - cargoVehicleOwned
        - safetyOrganizationAssigned
