openapi: 3.0.1
info:
  title: Hazardous Machine Protection API
  version: 1.0.1
  description: 유해·위험 기계·기구의 방호조치 상태 관리 API

paths:
  /api/site-status/{siteId}/hazard-machines:
    get:
      summary: 유해·위험 기계·기구 목록 조회
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HazardMachine'

    post:
      summary: 유해·위험 기계·기구 정보 등록
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HazardMachine'
      responses:
        '200':
          description: 등록 성공

  /api/site-status/{siteId}/hazard-machines/{machineId}:
    put:
      summary: 유해·위험 기계·기구 정보 수정
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
        - name: machineId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HazardMachine'
      responses:
        '200':
          description: 수정 성공

    delete:
      summary: 유해·위험 기계·기구 정보 삭제
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
        - name: machineId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 삭제 성공

components:
  schemas:
    HazardMachine:
      type: object
      required:
        - type
        - count
        - protectionDetails
      properties:
        type:
          type: string
          description: |
            기계·기구 종류
            - 예시: 예초기, 원심기, 지게차, 공기압축기, 포장기, 금속절단기 등
            - 산업안전보건법상 유해·위험 기계 기구 목록에 해당하는 장비
          example: 예초기

        count:
          type: integer
          description: |
            해당 기계·기구의 보유 대수
          example: 3

        protectionDetails:
          type: string
          description: |
            방호조치 상세 설명
            - 설치된 방호장치나 예방장치의 명칭 또는 기능
            - 예: 날접촉 예방장치, 낙하방지 덮개 등
          example: 날접촉 예방장치(두께 2mm, 밀림 방지 구조)

        protectionImplemented:
          type: boolean
          description: |
            방호조치 실시 여부
            - true: 방호조치가 되어 있음
            - false: 방호조치가 되어 있지 않음
          example: true

        photoUrl:
          type: string
          format: uri
          description: |
            방호조치 증빙 사진의 URL
            - 기계에 설치된 방호장치의 실제 사진
            - 등록 시 이미지를 업로드하여 노출
          example: https://example.com/photo.jpg
