openapi: 3.0.1
info:
  title: Hazardous Machine Protection API
  version: 1.0.0
  description: 유해·위험 기계·기구의 방호조치 상태 관리 API

paths:
  /api/site-status/{siteId}/hazard-machines:
    get:
      summary: 유해·위험 기계·기구 목록 조회
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HazardMachine'

    post:
      summary: 유해·위험 기계·기구 정보 등록
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HazardMachine'
      responses:
        '200':
          description: 등록 성공

  /api/site-status/{siteId}/hazard-machines/{machineId}:
    put:
      summary: 유해·위험 기계·기구 정보 수정
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
        - name: machineId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HazardMachine'
      responses:
        '200':
          description: 수정 성공

    delete:
      summary: 유해·위험 기계·기구 정보 삭제
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
        - name: machineId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 삭제 성공

components:
  schemas:
    HazardMachine:
      type: object
      properties:
        type:
          type: string
          example: 예초기
        count:
          type: integer
          example: 3
        protectionDetails:
          type: string
          example: 날접촉 예방장치(덮개 등)
        protectionImplemented:
          type: boolean
          example: true
        photoUrl:
          type: string
          format: uri
          example: https://example.com/photo.jpg
      required:
        - type
        - count
        - protectionDetails