openapi: 3.0.3
info:
  title: Site Status API
  version: 1.0.1
  description: 사업장 현황 관리 API

paths:
  /api/site-status:
    post:
      summary: 사업장 및 근로자 등록
      tags: [SiteStatus]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SiteStatusRequest'
      responses:
        '200':
          description: 등록 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteStatusPostResponse'

    get:
      summary: 사업장 목록 조회 (페이징)
      tags: [SiteStatus]
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: 페이지 번호
        - in: query
          name: size
          schema:
            type: integer
            default: 10
          description: 페이지 당 항목 수
        - in: query
          name: department
          schema:
            type: string
          description: 부서명 필터
        - in: query
          name: siteName
          schema:
            type: string
          description: 사업장 이름 필터
      responses:
        '200':
          description: 목록 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteStatusListResponse'

  /api/site-status/{siteId}:
    get:
      summary: 사업장 상세 조회
      tags: [SiteStatus]
      parameters:
        - in: path
          name: siteId
          required: true
          schema:
            type: integer
          description: 조회할 사업장 ID
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteStatusDetailResponse'

    put:
      summary: 사업장 정보 수정
      tags: [SiteStatus]
      parameters:
        - in: path
          name: siteId
          required: true
          schema:
            type: integer
          description: 수정할 사업장 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SiteStatusRequest'
      responses:
        '200':
          description: 수정 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'

    delete:
      summary: 사업장 정보 삭제
      tags: [SiteStatus]
      parameters:
        - in: path
          name: siteId
          required: true
          schema:
            type: integer
          description: 삭제할 사업장 ID
      responses:
        '200':
          description: 삭제 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'

components:
  schemas:
    SiteStatusRequest:
      type: object
      properties:
        siteName:
          type: string
          description: 사업장 이름
          example: "중앙산림청"
        department:
          type: string
          description: 부서명
          example: "산림청 보호과"
        period:
          type: object
          properties:
            startDate:
              type: string
              format: date
              description: 작업 시작일
              example: "2025-01-01"
            endDate:
              type: string
              format: date
              description: 작업 종료일
              example: "2025-12-31"
        address:
          type: string
          description: 사업장 주소
          example: "서울시 종로구 세종대로 1"
        workDetails:
          type: array
          items:
            type: string
          description: 주요 작업 내용
          example: ["중앙산림 조사", "죽은나무 제거"]
        manager:
          type: object
          description: 사업장 관리자 정보
          properties:
            position:
              type: string
              description: 직급
              example: "과장"
            title:
              type: string
              description: 직책
              example: "부서장"
            name:
              type: string
              description: 성명
              example: "홍길동"
        supervisor:
          type: object
          description: 현장 감독자 정보
          properties:
            position:
              type: string
              description: 직급
              example: "팀장"
            title:
              type: string
              description: 직책
              example: "현장감독"
        responsibles:
          type: array
          description: 사업 담당자 목록
          items:
            type: object
            properties:
              no:
                type: integer
                description: 일련번호
                example: 1
              position:
                type: string
                description: 직급
                example: "직급"
              name:
                type: string
                description: 성명
                example: "홍길수"
              phone:
                type: string
                description: 전화번호
                example: "010-1234-5678"
        employees:
          type: array
          description: 근로자 정보 리스트
          items:
            type: object
            properties:
              employmentType:
                type: string
                description: 고용형태
                example: "직영"
              name:
                type: string
                description: 성명
                example: "이영희"
              birthDate:
                type: string
                format: date
                description: 생년월일
                example: "1990-05-10"
              phone:
                type: string
                description: 전화번호
                example: "010-5678-1234"
              workingDays:
                type: integer
                description: 근무 일수
                example: 30
              resigned:
                type: boolean
                description: 퇴사 여부
                example: false

    SiteStatusPostResponse:
      type: object
      properties:
        code:
          type: string
          description: 응답 코드
          example: "0000"
        message:
          type: string
          description: 응답 메시지
          example: "등록 성공"
        siteId:
          type: integer
          description: 생성된 사업장 ID
          example: 123

    SiteStatusListResponse:
      type: object
      properties:
        totalCount:
          type: integer
          description: 전체 사업장 수
          example: 100
        page:
          type: integer
          description: 현재 페이지
          example: 1
        size:
          type: integer
          description: 페이지당 수량
          example: 10
        data:
          type: array
          items:
            $ref: '#/components/schemas/SiteStatusSummary'

    SiteStatusSummary:
      type: object
      properties:
        siteId:
          type: integer
          description: 사업장 ID
          example: 123
        siteName:
          type: string
          description: 사업장 이름
          example: "서울조사청"
        department:
          type: string
          description: 부서명
          example: "산림조사부"
        period:
          type: object
          properties:
            startDate:
              type: string
              format: date
              example: "2025-01-01"
            endDate:
              type: string
              format: date
              example: "2025-12-31"
        address:
          type: string
          description: 주소
          example: "서울특별시 종로구"
        workers:
          $ref: '#/components/schemas/WorkersSummary'

    WorkersSummary:
      type: object
      properties:
        total:
          type: integer
          description: 전체 인원 수
          example: 10
        publicServant:
          type: integer
          description: 공무원 수
          example: 1
        govEmployee:
          type: integer
          description: 공무직 수
          example: 2
        police:
          type: integer
          description: 청원경찰 수
          example: 1
        contractWorkers:
          type: object
          properties:
            direct:
              type: integer
              description: 직영 근로자 수
              example: 3
            public:
              type: integer
              description: 공공근로 수
              example: 1
            forest:
              type: integer
              description: 산불감시원 수
              example: 1
            other:
              type: integer
              description: 기타 인원 수
              example: 1

    SiteStatusDetailResponse:
      allOf:
        - $ref: '#/components/schemas/SiteStatusRequest'
        - type: object
          properties:
            siteId:
              type: integer
              description: 사업장 ID
              example: 123
            workers:
              $ref: '#/components/schemas/WorkersSummary'

    CommonResponse:
      type: object
      properties:
        code:
          type: string
          example: "0000"
          description: 응답 코드
        message:
          type: string
          description: 결과 메시지
          example: "처리 완료"
