openapi: 3.0.1
info:
  title: Site Overview API
  version: 1.0.0
  description: 사업장 개요 전체 데이터 관리 API

paths:
  /api/site-status/{siteId}/overview:
    get:
      summary: 사업장 개요 조회
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteOverview'

    post:
      summary: 사업장 개요 저장 (등록/수정 통합)
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SiteOverview'
      responses:
        '200':
          description: 저장 성공

    delete:
      summary: 사업장 개요 전체 삭제
      parameters:
        - name: siteId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 삭제 성공

components:
  schemas:
    SiteOverview:
      type: object
      properties:
        siteInfo:
          $ref: '#/components/schemas/SiteInfo'
        accidentHistory:
          type: array
          items:
            $ref: '#/components/schemas/AccidentRecord'
        inspectionMachines:
          type: array
          items:
            $ref: '#/components/schemas/InspectionMachine'
        hazardMachines:
          type: array
          items:
            $ref: '#/components/schemas/HazardMachine'
        cargoVehicles:
          type: array
          items:
            $ref: '#/components/schemas/CargoVehicle'
        safetyOrganization:
          $ref: '#/components/schemas/SafetyOrganization'
        obligationChecklist:
          type: array
          items:
            $ref: '#/components/schemas/ObligationItem'

    SiteInfo:
      type: object
      properties:
        companyName:
          type: string
          description: 회사명
          example: "안전건설(주)"
        period:
          type: string
          description: 공사 기간
          example: "2024.01 ~ 2024.12"
        supervisingEntities:
          type: array
          description: 감독기관 목록
          items:
            type: string
          example: ["고용노동부", "안전관리공단"]
        safetyManager:
          type: string
          description: 안전관리자 이름
          example: "홍길동"
        managerPosition:
          type: string
          description: 직책
          example: "안전관리부장"
        managerPhone:
          type: string
          description: 연락처
          example: "010-1234-5678"
        siteWorkers:
          type: array
          description: 현장근로자 유형
          items:
            type: string
          example: ["직영", "하도급"]

    AccidentRecord:
      type: object
      properties:
        date:
          type: string
          format: date
          description: 사고 발생일
          example: "2024-03-15"
        victim:
          type: string
          description: 피해자 이름
          example: "김철수"
        employmentType:
          type: string
          description: 고용 형태
          example: "하도급"
        injuryType:
          type: string
          description: 부상 종류
          example: "골절"
        detail:
          type: string
          description: 사고 상세 내용
          example: "작업 중 추락"
        hasReport:
          type: boolean
          description: 신고 여부
          example: true

    InspectionMachine:
      type: object
      properties:
        name:
          type: string
          description: 기계명
          example: "지게차"
        capacity:
          type: string
          description: 용량
          example: "3톤"
        pressure:
          type: string
          description: 압력
          example: "10bar"
        unit:
          type: string
          description: 단위
          example: "bar"
        process:
          type: string
          description: 사용 공정
          example: "운반작업"
        msdsAttachment:
          type: string
          description: MSDS 첨부파일 링크
          example: "https://example.com/msds.pdf"
        msdsVersion:
          type: string
          description: MSDS 버전
          example: "v2.0"

    HazardMachine:
      type: object
      properties:
        type:
          type: string
          description: 기계 유형
          example: "컨베이어"
        hasShield:
          type: boolean
          description: 방호장치 여부
          example: true
        details:
          type: string
          description: 상세내용
          example: "정비 중 위험 노출 있음"
        isImplemented:
          type: boolean
          description: 개선 여부
          example: false
        photoUrl:
          type: string
          description: 사진 링크
          example: "https://example.com/hazard.jpg"

    CargoVehicle:
      type: object
      properties:
        plateNumber:
          type: string
          description: 차량 번호
          example: "12가1234"
        model:
          type: string
          description: 차량 모델
          example: "포터2"
        maxLoad:
          type: string
          description: 최대 적재량
          example: "1톤"
        vehicleType:
          type: string
          description: 차량 종류
          example: "화물차"

    SafetyOrganization:
      type: object
      properties:
        general:
          type: string
          description: 총괄 책임자
          example: "홍길동"
        manager:
          type: string
          description: 안전관리자
          example: "김안전"
        supervisor:
          type: string
          description: 현장소장
          example: "이현장"
        healthManager:
          type: string
          description: 보건관리자
          example: "최보건"
        guardian:
          type: string
          description: 보호 담당자
          example: "장보호"

    ObligationItem:
      type: object
      properties:
        itemNo:
          type: integer
          description: 항목 번호
          example: 1
        title:
          type: string
          description: 항목 제목
          example: "보호구 착용 여부"
        checked:
          type: string
          enum: ["이행", "미이행", "해당없음"]
          description: 이행 상태
          example: "이행"
